### ISSUE TITLE
Integrate an responsive Slider and Lightbox

### ISSUE THREAD

**Issue by mneuhaus** [famelo/TYPO3#17]
We should have a proper responsive Slider and Lightbox working out of the box.

For the TYPO3 side we should probably use the extension [imagecycle](http://typo3.org/extensions/repository/view/imagecycle).

For the Slider part i currently see 2 main libraries that seem to be quite good:
- [unslider](http://unslider.com/)
- [Refineslide](http://alexdunphy.github.io/refineslide/#)

For the Lightbox part this one seems quite nice:

[Magnific Popup](http://dimsemenov.com/plugins/magnific-popup/)

@SvenEs do you have any other suggestions?

**Comment by ssteinker** [comment]
wb the [Flexslider](http://flexslider.woothemes.com/)?
